name: worldmix
description: List, search, mix and get what you want.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  momentum: ^1.3.2
  shared_preferences: ^0.5.6+2
  flutter_svg: ^0.17.4
  flutter_launcher_icons: ^0.7.5
  flutter_form_builder: ^3.9.0
  intl: ^0.16.0
  firebase_core: ^0.4.4
  firebase_analytics: ^5.0.15
  firebase_auth: ^0.15.3+1
  sqflite: any
  http:
  image_picker: ^0.6.7+4
  the_validator: ^1.0.1
  flutter_local_notifications: ^1.4.4+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/